name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        submodules: recursive
        #settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: List submodule content
      run: |
        ls -al .
        ls -al dictionary-jpa
    - name: Build submodule
      run: mvn -B compile --file dictionary-jpa/pom.xml
