name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        fetch-depth: 0
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
        #settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: list directory content
      run: |
        ls -al
    - name: Build submodule
      run: mvn -B compile --file dictionary-jpa/pom.xml
